# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e78ea4d4fe7f1ce697756067bb0d4151"
name = "custom-payment-ui-v1"
application_url = "https://declined-adobe-pmid-trace.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quiz-store-test-wad.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://declined-adobe-pmid-trace.trycloudflare.com/auth/callback",
  "https://declined-adobe-pmid-trace.trycloudflare.com/auth/shopify/callback",
  "https://declined-adobe-pmid-trace.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
